# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 341b31addf3311a58aaee40ed8ae368ec2b9102c77610764de6c56262fc98ca34158675980af628792129fb1e21514774b51500b28956d3a54bcca19a41b0b0a

test:
  secret_key_base: e1e167a69403a0b2002373caffcbe3696901bd07efaff3486696a5a21c0075e838931dc58efad6f0c0676c7f500a1d1188375474134995df164222c96c920906

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
